const countries = ['Maldives', 'America', 'Dubai', 'Germany', 'Japan'];
console.log("orignal order");
console.log(countries);
console.log("\n alphabetical order");
console.log([...countries].sort());
console.log("\n orignal order verified");
console.log(countries);
console.log("\n Reverse Alphabetical Order");
console.log([...countries].sort().reverse());
console.log("\n orignal order");
console.log(countries);
console.log("\n Reversed order");
console.log(countries.reverse());
console.log("\norignal array");
console.log(countries);
console.log("\n Alphabetical Order");
console.log(countries.sort());
console.log("\n Reverse Alphabetical order");
console.log(countries.sort().reverse());
export {};
