let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
let my_name = "humayun";
console.log("Is my_name == 'humayun'I predict true");
console.log(my_name === 'humayun');
let my_car = "hyundai";
console.log("is my_car == 'hyundai'I predict true");
console.log(my_car == 'hyundai');
let vegetable = "potato";
console.log("Is vegetable =='potato' I guess true");
console.log(vegetable === 'potato');
let sports = "cricket";
console.log("Is sports==='cricket'I guess true");
console.log(sports === 'cricket');
let num = 5;
console.log("Is num < 1 ? I guess false");
console.log(num < 1);
let teacher = "sir hammad";
console.log("Is teacher == 'sir asif' I guess false");
console.log(teacher === 'sir asif');
let a = 5;
let b = 6;
console.log("Is a === b ? I guess false");
console.log(a === b);
let mobile = "iphone";
console.log("Is mobile === samsung?I guess false");
console.log(mobile == 'samsung');
let primeminister = "Imran Khan";
console.log("Is primeminister == asif zardari?I guess false");
console.log(primeminister === 'asif zardari');
export {};
